version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - postgres-network
    volumes:
      - ./db-data/:/var/lib/postgresql/data/

networks:
  postgres-network:
    driver: bridge